- name: Delete all Docker EC2 instances and related components
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: ec2/load-balancer/delete }
    - { role: ec2/asg/delete }
    - { role: route53/record/delete }