- name: Install Docker and ensure it's at the latest version
  yum:
    name: docker
    state: latest
  become: true
- service:
    name: docker
    state: started
    enabled: yes
  become: true
- user:
    name: docker
    groups: docker
    shell: /bin/bash
    append: yes
  become: true
# - user:
#     name: ec2-user
#     groups: docker
#     append: yes
#   become: true
# - name: Reset connection so group is applied to user
#   meta: reset_connection
- name: Install pip
  yum:
    name: python2-pip
    state: latest
  become: true
- name: Install Docker Python bindings
  pip:
    name: docker-py
  become: true