- name: Create Auto Scaling Group
  local_action:
    module: ec2_asg
    name: dockerASG
    region: '{{ aws_region }}'
    launch_config_name: '{{ lc.name }}'
    min_size: 1
    max_size: 5
    wait_for_instances: True
    availability_zones: ['us-east-2a', 'us-east-2b', 'us-east-2c']
    vpc_zone_identifier: '{{ vpc_zones }}'
    target_group_arns: '{{elb_tg.target_group_arn}}'
    desired_capacity: 2
    tags:
      - function: docker
        billingGroup: Work
- ec2_asg_facts:
    name: dockerASG
    region: '{{ aws_region }}'
  register: asg_facts
- ec2_instance_facts:
    region: us-east-2
    instance_ids: '{{item.instance_id}}'
  register: asg_instance_facts
  with_items: '{{asg_facts.results[0].instances}}'
- name: Get IP addresses
  add_host:
    name: '{{item.instances[0].network_interfaces[0].private_dns_name}}'
    groups: asg_instances
  with_items: '{{asg_instance_facts.results}}'
- name: Wait for SSH
  wait_for:
    host: '{{item}}'
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: '{{groups.asg_instances}}'
