tasks:
  - name: Install RPM Python bindings
    become: yes
    raw: yum install rpm-python -y

  - name: Update all software
    become: yes
    yum:
      update_cache: yes
      name: "*"
      state: latest