- name: Create Elastic Load Balancer
  ec2_elb_lb:
    name: httpDockerLB
    state: present
    region: us-east-2
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
        
    security_group_names: dockerSG
    zones: ['us-east-2a', 'us-east-2b', 'us-east-2c']
