- name: Check if python-apt is installed
  raw: apt list --installed
  register: aptlist
- name: Install python-apt
  raw: apt install python-apt
  become: True
  when: python-apt.stdout.find('python-apt') == -1
- name: Update and upgrade using apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    # name: "*"
    upgrade: safe
  become: True